### ISSUE TITLE
Ejercicio 2 - d) Que es el mcp3304(spi) y como lo utilizaría para hacer una shield que controle 8  sensores?

### ISSUE THREAD

**Issue by FedeBirge** [ISPC-TST-Electronica-Microcontrolada/Grupo1#57]

**Comment by FedeBirge** [comment]
Reasigné tarea para el nuevo integrante del grupo

**Comment by estebancarrizo** [comment]
[Prácticas de IO - Shields v1.0.docx](https://github.com/ISPC-TST-Electronica-Microcontrolada/Grupo1/files/9483717/Practicas.de.IO.-.Shields.v1.0.docx)
